apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: mysql-cont
        image: mysql:5.7
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: storage
          mountPath: /var/lib/mysql
        env:
        - name: MYSQL_DATABASE
          value: arunsql
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: backend
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
  clusterIP: None  # Headless service to enable direct communication
